/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiprediksimasastudi_3;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author aspire
 */
public class data_mahasiswa extends javax.swing.JFrame {
private static class txt_kodetraining {
        public txt_kodetraining() {
        }
    }
String header[] = {"kode training", "angkatan", "jenis kelamin", "kota", "ipk", "konsentrasi", "status kelulusan"};
String header2[] = {"uraian data","jumlah"};
Connection con;
  Statement st;
  koneksi kon = new koneksi();
  private DefaultTableModel tabMode;
    private DefaultTableModel tabMode2;
  String query;
    /**
     * Creates new form data_mahasiswa
     */
    public data_mahasiswa() throws SQLException {
        initComponents();
        TampilDataTabel();
        bersih();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        cmb_angkatan = new javax.swing.JComboBox();
        cmb_jeniskelamin = new javax.swing.JComboBox();
        cmb_kota = new javax.swing.JComboBox();
        cmb_konsentrasi = new javax.swing.JComboBox();
        cmb_statuskelulusan = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txt_searchnim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myTabel = new javax.swing.JTable();
        btn_search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_clean = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbPilih = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt_kodetraining = new javax.swing.JTextField();
        cmb_ipk = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("TempoFont", 1, 36)); // NOI18N
        jLabel1.setText("Data Mahasiswa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Angkatan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Kota");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("IPK");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Konsentrasi");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Status Kelulusan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 80, -1));

        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_exit.setText("Close");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 80, -1));

        cmb_angkatan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_angkatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009" }));
        jPanel1.add(cmb_angkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        cmb_jeniskelamin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "laki-laki", "perempuan" }));
        jPanel1.add(cmb_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, -1));

        cmb_kota.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_kota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kotamadya", "kabupaten" }));
        cmb_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kotaActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, -1));

        cmb_konsentrasi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_konsentrasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(cmb_konsentrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        cmb_statuskelulusan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_statuskelulusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "tepat", "terlambat" }));
        cmb_statuskelulusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statuskelulusanActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_statuskelulusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Pencarian data berdasarkan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        txt_searchnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchnimActionPerformed(evt);
            }
        });
        jPanel1.add(txt_searchnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 120, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Data Training");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        myTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        myTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myTabel);
        tabMode=new DefaultTableModel(null,header);
        myTabel.setModel(tabMode);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 790, 100));

        btn_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 100, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 50));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, -1));

        btn_clean.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_clean.setText("Clean");
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 90, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        tabMode2=new DefaultTableModel(null,header2);
        jTable2.setModel(tabMode2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 400, 90));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Keterangan Kode Konsentrasi :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("1 : Rekayasa Perangkat Lunak");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("2 : Jaringan Komputer/ Keamanan Informasi");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("4 : Sistem Informasi");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("3 : Grafika Komputer");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        cmbPilih.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbPilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kode_training", "angkatan", "jenis_kelamin", "kota", "ipk", "konsentrasi", "status_kelulusan" }));
        cmbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Kode Training");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txt_kodetraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, 30));

        cmb_ipk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_ipk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sangat_baik", "baik", "cukup" }));
        cmb_ipk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ipkActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_ipk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Keterangan Status IPK :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("cukup = 2.00 - 2.55 ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("baik = 2.56 - 3.00 ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("sangat_baik = > 3.00 ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Uraian Jumlah Data");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background.png"))); // NOI18N
        jPanel1.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchnimActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        Hapus();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Simpan(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        CariDataTabel();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void myTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTabelMouseClicked
        Lihat();        // TODO add your handling code here:
    }//GEN-LAST:event_myTabelMouseClicked

    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        bersih();// TODO add your handling code here:
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        new menuawal_admin(query).show();
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void cmbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPilihActionPerformed

    private void cmb_statuskelulusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statuskelulusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statuskelulusanActionPerformed

    private void cmb_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kotaActionPerformed

    private void cmb_ipkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ipkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ipkActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
           // for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               // if ("Nimbus".equals(info.getName())) {
                  //  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   // break;
               // }
           // }
       // } catch (ClassNotFoundException ex) {
          //  java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // } catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
         //   java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
         //   java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
                //try {
                  //  new data_mahasiswa().setVisible(true);
               // } //catch (SQLException ex) {
                    //Logger.getLogger(data_mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
       // }
                
           // }
       // });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cmbPilih;
    private javax.swing.JComboBox cmb_angkatan;
    private javax.swing.JComboBox cmb_ipk;
    private javax.swing.JComboBox cmb_jeniskelamin;
    private javax.swing.JComboBox cmb_konsentrasi;
    private javax.swing.JComboBox cmb_kota;
    private javax.swing.JComboBox cmb_statuskelulusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JTable myTabel;
    private javax.swing.JTextField txt_kodetraining;
    private javax.swing.JTextField txt_searchnim;
    // End of variables declaration//GEN-END:variables
void Simpan(){
        String kodetraining=txt_kodetraining.getText().toString();
        String angkatan=cmb_angkatan.getSelectedItem().toString();
        String jeniskelamin=cmb_jeniskelamin.getSelectedItem().toString();
        String kota=cmb_kota.getSelectedItem().toString();
        String ipk=cmb_ipk.getSelectedItem().toString();
        String konsentrasi=cmb_konsentrasi.getSelectedItem().toString();
        String status_kelulusan=cmb_statuskelulusan.getSelectedItem().toString();
       
       
        try{
        kon.QUERY("INSERT INTO `data_mahasiswa`(`kode_training`, `angkatan`, `jenis_kelamin`, `kota`, `ipk`, `konsentrasi`, `status_kelulusan`) VALUE(NULL,'"+angkatan+"','"+jeniskelamin+"','"+kota+"','"+ipk+"','"+konsentrasi+"','"+status_kelulusan+"')","Simpan"); 
        TampilDataTabel(); 
        bersih(); 
        
        }catch(Exception sqle){
            //JOptionPane.showMessageDialog(rootPane,"Data Gagal Simpan"+sqle.getMessage());
        }
    }

void Hapus(){
    String kodetraining=txt_kodetraining.getText();
     try{
         kon.QUERY("DELETE FROM data_mahasiswa WHERE kode_training ='"+kodetraining+"'","Hapus");
     TampilDataTabel();
     bersih();     
     }
catch (Exception sqle){
        // JOptionPane.showMessageDialog(rootPane,"Data Gagal Hapus"+sqle.getMessage());
    	 } 
    }

private void TampilDataTabel() throws SQLException{
    
    
   int j2001=0;
   int j2001T=0;
   int j2001L=0;

   int j2002=0;
   int j2002T=0;
    int j2002L=0;
   
   int j2003=0;
   int j2003T=0;
   int j2003L=0;
   
   int j2004=0;
   int j2004T=0;
   int j2004L=0;
   
   int j2005=0;
   int j2005T=0;
   int j2005L=0;
   
   int j2006=0;
   int j2006T=0;
   int j2006L=0;
   
   int j2007=0;
   int j2007T=0;
   int j2007L=0;
   
   int j2008=0;
   int j2008T=0;
   int j2008L=0;
   
   int j2009=0;
   int j2009T=0;
   int j2009L=0;
   
   int jpria=0;
   int jpriaT=0;
   int jpriaL=0;
   
   int jwanita=0;
   int jwanitaT=0;
   int jwanitaL=0;
   
   int jkotamadya=0;
   int jkotamadyaT=0;
   int jkotamadyaL=0;
   
   int jkabupaten=0;
   int jkabupatenT=0;
   int jkabupatenL=0;
   
   int jsangat_baik=0;
   int jsangat_baikT=0;
   int jsangat_baikL=0;
   
   int jbaik=0;
   int jbaikT=0;
   int jbaikL=0;
   
   int jcukup=0;
   int jcukupT=0;
   int jcukupL=0;
   
   
   int jipk=0;
   double dn=0;
   int ipkT=0;
   int ipkL=0;
   
   int j1=0;
   int j1T=0;
   int j1L=0;
   
   int j2=0;
   int j2T=0;
   int j2L=0;
   
   int j3=0;
   int j3T=0;
   int j3L=0;
   
   int j4=0;
   int j4T=0;
   int j4L=0;
   
   
    
   
   
   removeTable2();
      {
          con=kon.open();
          st=con.createStatement();        
          query="SELECT * FROM data_mahasiswa";
          ResultSet rs=st.executeQuery(query);
          
          while(rs.next()){
            String kode_training=rs.getString("kode_training");
            String angkatan=rs.getString("angkatan");  
            String jenis_kelamin=rs.getString("jenis_kelamin");
            String kota=rs.getString("kota");
            String ipk=rs.getString("ipk");
            String konsentrasi=rs.getString("konsentrasi");
            
            try{
            dn=Double.parseDouble(ipk);
            }
            catch(Exception ee){dn=0;}

            
            String status_kelulusan=rs.getString("status_kelulusan");
            
         
            if(angkatan.equalsIgnoreCase("2001")){
                j2001++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2001T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2001L++;}
            }
            
            if(angkatan.equalsIgnoreCase("2002")){
                j2002++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2002T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2002L++;}
            }
            
            if(angkatan.equalsIgnoreCase("2003")){
                j2003++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2003T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2003L++;}
            }
            
            if(angkatan.equalsIgnoreCase("2004")){
                j2004++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2004T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2004L++;}
            }
            
            if(angkatan.equalsIgnoreCase("2005")){
                j2005++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2005T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2005L++;}
            }
            
            if(angkatan.equalsIgnoreCase("2006")){
                j2006++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2006T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2006L++;}
                
            }
            
            if(angkatan.equalsIgnoreCase("2007")){
                j2007++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2007T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2007L++;}
                
            }
            
            if(angkatan.equalsIgnoreCase("2008")){
                j2008++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2008T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2008L++;}
                
            }
            
            if(angkatan.equalsIgnoreCase("2009")){
                j2009++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){j2009T++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2009L++;}
                
            }
             if(jenis_kelamin.equalsIgnoreCase("perempuan")){
                jwanita++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){jwanitaT++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){jwanitaL++;}
            } 
           
            
             if(jenis_kelamin.equalsIgnoreCase("laki-laki")){
                jpria++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){jpriaT++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){jpriaL++;}
                
             }
            if(kota.equalsIgnoreCase("kotamadya")){
                jkotamadya++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){jkotamadyaT++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){jkotamadyaL++;}
            } 
            
            if(kota.equalsIgnoreCase("kabupaten")){
                jkabupaten++;
                if(status_kelulusan.equalsIgnoreCase("tepat")){jkabupatenT++;}
                else if(status_kelulusan.equalsIgnoreCase("terlambat")){jkabupatenL++;}
            } 
           
            
             /*if(dn>40){
               jipk++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){ipkT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){ipkL++;}   
            }
             else              if(dn>30){
               jipk++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){ipkT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){ipkL++;}   
            }
             else  {
               jipk++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){ipkT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){ipkL++;}   
            }*/
            
           if(ipk.equalsIgnoreCase("sangat_baik")){
               jsangat_baik++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){jsangat_baikT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){jsangat_baikL++;}
            }
           
           if(ipk.equalsIgnoreCase("baik")){
               jbaik++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){jbaikT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){jbaikL++;}
            }
           
           if(ipk.equalsIgnoreCase("cukup")){
               jcukup++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){jcukupT++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){jcukupL++;}
            }

            if(konsentrasi.equalsIgnoreCase("1")){
               j1++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){j1T++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){j1L++;}
            }
             
            if(konsentrasi.equalsIgnoreCase("2")){
               j2++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){j2T++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){j2L++;}
            }
            
            if(konsentrasi.equalsIgnoreCase("3")){
               j3++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){j3T++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){j3L++;}
            }
            
            if(konsentrasi.equalsIgnoreCase("4")){
               j4++;
               if(status_kelulusan.equalsIgnoreCase("tepat")){j4T++;}
               else if(status_kelulusan.equalsIgnoreCase("terlambat")){j4L++;}
            }
            String data[] = {kode_training, angkatan, jenis_kelamin, kota, ipk, konsentrasi, status_kelulusan};
            tabMode.addRow(data);     
      }
       {
           String sqle = null;
             // JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
       } 
      
      
      String mdata1[] = {"Jumlah 2001" ,String.valueOf(j2001)};
        tabMode2.addRow(mdata1);
      String mdata2[] = {"Jumlah 2001 Tepat" ,String.valueOf(j2001T)};
        tabMode2.addRow(mdata2);
      String mdata3[] = {"Jumlah 2001 Terlambat" ,String.valueOf(j2001L)};
        tabMode2.addRow(mdata3);
      String mdata4[] = {"Jumlah 2002" ,String.valueOf(j2002)};
        tabMode2.addRow(mdata4);
      String mdata5[] = {"Jumlah 2002 Tepat" ,String.valueOf(j2002T)};
        tabMode2.addRow(mdata5);
      String mdata6[] = {"Jumlah 2002 Terlambat" ,String.valueOf(j2002L)};
        tabMode2.addRow(mdata6);
      String mdata7[] = {"Jumlah 2003" ,String.valueOf(j2003)};
        tabMode2.addRow(mdata7); 
      String mdata8[] = {"Jumlah 2003 Tepat" ,String.valueOf(j2003T)};
        tabMode2.addRow(mdata8);  
      String mdata9[] = {"Jumlah 2003 Terlambat" ,String.valueOf(j2003L)};
        tabMode2.addRow(mdata9); 
      String mdata10[] = {"Jumlah 2004" ,String.valueOf(j2004)};
        tabMode2.addRow(mdata10); 
      String mdata11[] = {"Jumlah 2004 Tepat" ,String.valueOf(j2004T)};
        tabMode2.addRow(mdata11); 
      String mdata12[] = {"Jumlah 2004 Terlambat" ,String.valueOf(j2004L)};
        tabMode2.addRow(mdata12);  
      String mdata13[] = {"Jumlah 2005" ,String.valueOf(j2005)};
        tabMode2.addRow(mdata13);  
      String mdata14[] = {"Jumlah 2005 Tepat" ,String.valueOf(j2005T)};
        tabMode2.addRow(mdata14); 
     String mdata15[] = {"Jumlah 2005 Terlambat" ,String.valueOf(j2005L)};
        tabMode2.addRow(mdata15);  
     String mdata16[] = {"Jumlah 2006" ,String.valueOf(j2006)};
        tabMode2.addRow(mdata16);  
     String mdata17[] = {"Jumlah 2006 Tepat" ,String.valueOf(j2006T)};
        tabMode2.addRow(mdata17);
     String mdata18[] = {"Jumlah 2006 Terlambat" ,String.valueOf(j2006L)};
        tabMode2.addRow(mdata18); 
    String mdata19[] = {"Jumlah 2007" ,String.valueOf(j2007)};
        tabMode2.addRow(mdata19);      
    String mdata20[] = {"Jumlah 2007 Tepat" ,String.valueOf(j2007T)};
        tabMode2.addRow(mdata20);   
    String mdata21[] = {"Jumlah 2007 Terlambat" ,String.valueOf(j2007L)};
        tabMode2.addRow(mdata21); 
    String mdata22[] = {"Jumlah 2008" ,String.valueOf(j2008)};
        tabMode2.addRow(mdata22); 
    String mdata23[] = {"Jumlah 2008 Tepat" ,String.valueOf(j2008T)};
        tabMode2.addRow(mdata23);
    String mdata24[] = {"Jumlah 2008 Terlambat" ,String.valueOf(j2008L)};
        tabMode2.addRow(mdata24);
    String mdata25[] = {"Jumlah 2009" ,String.valueOf(j2009)};
        tabMode2.addRow(mdata25);
    String mdata26[] = {"Jumlah 2009 Tepat" ,String.valueOf(j2009T)};
        tabMode2.addRow(mdata26);
    String mdata27[] = {"Jumlah 2009 Terlambat" ,String.valueOf(j2009L)};
        tabMode2.addRow(mdata27);
    String mdata28[] = {"Jumlah laki-laki" ,String.valueOf(jpria)};
        tabMode2.addRow(mdata28);
    String mdata29[] = {"Jumlah laki-laki Tepat" ,String.valueOf(jpriaT)};
        tabMode2.addRow(mdata29);
    String mdata30[] = {"Jumlah laki-laki Terlambat" ,String.valueOf(jpriaL)};
        tabMode2.addRow(mdata30);
    String mdata31[] = {"Jumlah perempuan" ,String.valueOf(jwanita)};
        tabMode2.addRow(mdata31);
    String mdata32[] = {"Jumlah perempuan Tepat" ,String.valueOf(jwanitaT)};
        tabMode2.addRow(mdata32);
    String mdata33[] = {"Jumlah  perempuan Terlambat" ,String.valueOf(jwanitaL)};
        tabMode2.addRow(mdata33);
    String mdata34[] = {"Jumlah kotamadya" ,String.valueOf(jkotamadya)};
        tabMode2.addRow(mdata34);
    String mdata35[] = {"Jumlah kotamadya Tepat" ,String.valueOf(jkotamadyaT)};
        tabMode2.addRow(mdata35);
    String mdata36[] = {"Jumlah kotamadya Terlambat" ,String.valueOf(jkotamadyaL)};
        tabMode2.addRow(mdata36);
    String mdata37[] = {"Jumlah kabupaten" ,String.valueOf(jkabupaten)};
        tabMode2.addRow(mdata37);
    String mdata38[] = {"Jumlah kabupaten Tepat" ,String.valueOf(jkabupatenT)};
        tabMode2.addRow(mdata38);
    String mdata39[] = {"Jumlah kabupaten Terlambat" ,String.valueOf(jkabupatenL)};
        tabMode2.addRow(mdata39);
    String mdata40[] = {"Jumlah sangat_baik" ,String.valueOf(jsangat_baik)};
        tabMode2.addRow(mdata40);
    String mdata41[] = {"Jumlah sangat_baik Tepat" ,String.valueOf(jsangat_baikT)};
        tabMode2.addRow(mdata41);
    String mdata42[] = {"Jumlah sangat_baik Terlambat" ,String.valueOf(jsangat_baikL)};
        tabMode2.addRow(mdata42);
    String mdata43[] = {"Jumlah baik" ,String.valueOf(jbaik)};
        tabMode2.addRow(mdata43);
    String mdata44[] = {"Jumlah baik Tepat" ,String.valueOf(jbaikT)};
        tabMode2.addRow(mdata44);
    String mdata45[] = {"Jumlah baik Terlambat" ,String.valueOf(jbaikL)};
        tabMode2.addRow(mdata45);
    String mdata46[] = {"Jumlah cukup" ,String.valueOf(jcukup)};
        tabMode2.addRow(mdata46);
    String mdata47[] = {"Jumlah cukup Tepat" ,String.valueOf(jcukupT)};
        tabMode2.addRow(mdata47);
    String mdata48[] = {"Jumlah cukup Terlambat" ,String.valueOf(jcukupL)};
        tabMode2.addRow(mdata48);
    String mdata49[] = {"Jumlah 1" ,String.valueOf(j1)};
        tabMode2.addRow(mdata49);
    String mdata50[] = {"Jumlah 1 Tepat" ,String.valueOf(j1T)};
        tabMode2.addRow(mdata50);
    String mdata51[] = {"Jumlah 1 Terlambat" ,String.valueOf(j1L)};
        tabMode2.addRow(mdata51);
    String mdata52[] = {"Jumlah 2" ,String.valueOf(j2)};
        tabMode2.addRow(mdata52);
    String mdata53[] = {"Jumlah 2 Tepat" ,String.valueOf(j2T)};
        tabMode2.addRow(mdata53);
    String mdata54[] = {"Jumlah 2 Terlambat" ,String.valueOf(j2L)};
        tabMode2.addRow(mdata54);
    String mdata55[] = {"Jumlah 3" ,String.valueOf(j3)};
        tabMode2.addRow(mdata55);
    String mdata56[] = {"Jumlah 3 Tepat" ,String.valueOf(j3T)};
        tabMode2.addRow(mdata56);
    String mdata57[] = {"Jumlah 3 Terlambat" ,String.valueOf(j3L)};
        tabMode2.addRow(mdata57);
    String mdata58[] = {"Jumlah 4" ,String.valueOf(j4)};
        tabMode2.addRow(mdata58);
    String mdata59[] = {"Jumlah 4 Tepat" ,String.valueOf(j4T)};
        tabMode2.addRow(mdata59);
    String mdata60[] = {"Jumlah 4 Terlambat" ,String.valueOf(j4L)};
        tabMode2.addRow(mdata60);
   
        
}
}


private void CariDataTabel(){
     removeTable();
     
     String pilih = cmbPilih.getSelectedItem().toString();
     String cari = txt_searchnim.getText().toString();
    
//kode_training, angkatan, jenis_kelamin, kota, ipk, konsentrasi, status_kelulusan    
      try{
          con=kon.open();
          st=con.createStatement();
          if(pilih.equalsIgnoreCase("kode_training")){
          query="SELECT * FROM data_mahasiswa where kode_training like '%"+cari+"%' order by kode_training asc";
          }
          else           if(pilih.equalsIgnoreCase("angkatan")){
          query="SELECT * FROM data_mahasiswa where angkatan like '%"+cari+"%' order by kode_training asc";
          }
          else           if(pilih.equalsIgnoreCase("jenis_kelamin")){
          query="SELECT * FROM data_mahasiswa where jenis_kelamin like '%"+cari+"%' order by kode_training asc";
          }
          else           if(pilih.equalsIgnoreCase("kota")){
          query="SELECT * FROM data_mahasiswa where kota like '%"+cari+"%' order by kode_training asc";
          }
          else           if(pilih.equalsIgnoreCase("ipk")){
          query="SELECT * FROM data_mahasiswa where ipk like '%"+cari+"%' order by kode_training asc";
          }
          else           if(pilih.equalsIgnoreCase("konsentrasi")){
          query="SELECT * FROM data_mahasiswa where konsentrasi like '%"+cari+"%' order by kode_training asc";
          }
   
          else           if(pilih.equalsIgnoreCase("status_kelulusan")){
          query="SELECT * FROM data_mahasiswa where status_kelulusan like '%"+cari+"%' order by kode_training asc";
          }

          System.out.println(query);
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
            String kodetraining=rs.getString("kode_training");
            String angkatan=rs.getString("angkatan");  
            String jeniskelamin=rs.getString("jenis_kelamin");
            String kota=rs.getString("kota");
            String ipk=rs.getString("ipk");
            String konsentrasi=rs.getString("konsentrasi");
            String status_kelulusan=rs.getString("status_kelulusan");
        
         
            String data[] = {kodetraining, angkatan, jeniskelamin, kota, ipk, konsentrasi, status_kelulusan};
            tabMode.addRow(data);
          }
      }catch(SQLException sqle){
          //JOptionPane.showMessageDialog(null,"Data Gagal Masuk Tabel"+sqle);
      }  
      
   
}

public void removeTable(){
        try{
            for(int t=tabMode.getRowCount();t>0;t--) {tabMode.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);
        }
        

}
public void removeTable2(){

        
         try{
            for(int t=tabMode2.getRowCount();t>0;t--) {tabMode2.removeRow(0);}
        }catch(Exception ex){ System.out.println(ex);
        }
}
void bersih(){
    txt_kodetraining.setText("");
    cmb_angkatan.setSelectedIndex(0);
    cmb_jeniskelamin.setSelectedIndex(0);
    cmb_kota.setSelectedIndex(0);
    cmb_ipk.setSelectedIndex(0);
    cmb_konsentrasi.setSelectedIndex(0);
    cmb_statuskelulusan.setSelectedIndex(0);
    
    
    btn_save.setEnabled(true);
    btn_delete.setEnabled(false);  
   
    }

 void Lihat(){
        //String kodetraining = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),0));
        //txt_kodetraining.setText(kodetraining);
        txt_kodetraining.setText(String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),0)));
        String angkatan = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),1));
        cmb_angkatan.setSelectedItem(angkatan);
        String  jk = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),2));
        cmb_jeniskelamin.setSelectedItem(jk);
        String  ko = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),3));
        cmb_kota.setSelectedItem(ko);
        String  ipk = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),4));
        cmb_ipk.setSelectedItem(ipk);
        String  ks = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),5));
        cmb_konsentrasi.setSelectedItem(ks);
        String  sk = String.valueOf(myTabel.getValueAt(myTabel.getSelectedRow(),6));
        cmb_statuskelulusan.setSelectedItem(sk);
       
        
        btn_save.setEnabled(false);
        btn_delete.setEnabled(true);
    
      
        }

}






